Contributing.md
linuxwhatelse/dups pull request #8
Opened 2018-10-11 01:04 UTC by HarryHeights

This is the contribution guide I promised to create. I guessed some things because I wasn't so sure. 

Are you okay with the fact that contributors can contribute however they like to the project? or you'll prefer they discuss with you first via an issue or an email.

2018-10-11 08:20 UTC, tadly requested changes
Just some typos I noticed that need fixing.
Apart from that this is looking good :)

2018-10-11 08:20 UTC, tadly commented on Contyributing.md
> +Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at activity-diary@rampro.de. The project team will review and investigate all compla
`activity-diary@rampro.de` that's not quite right now is it :)
For now you can use `support@linuxwhatelse.de`.

2018-10-12 08:50 UTC, tadly approved these changes

2018-10-12 08:52 UTC, tadly commented
I just noticed...
Could it be that the filename is `Contyributing.md`?

2018-10-12 10:00 UTC, HarryHeights commented
The filename is a mistake.

2018-10-12 10:00 UTC, HarryHeights commented
I think I changed the name in the last commit

2018-10-12 10:06 UTC, tadly commented
Not really, if you check your most recent commit a93245ca081cc4f67582da89442c8d2cd239cc56, it's still saying `Contyributing.md`

2018-10-12 10:15 UTC, HarryHeights commented
Okay, lemme change it

2018-10-12 10:40 UTC, merged